apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-l0o1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-l0o1
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-l0o1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-l0o1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-l0o1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-saug-tenant/nodejs-users/simple-nodejs-app-l0o1@sha256:2b55734556d856098a0cd2e6b94e59098680436558ac9e2ca8a60f24e4457559
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
